//
//  ContentView.swift
//  CollectionViewHomeScreen
//
//  Created by Leo Dion on 6/23/20.
//

import SwiftUI

struct SymbolName : Identifiable {
    let name : String
    let id : UUID = UUID()
}
let symbols = """
2.circle.fill
02.circle.fill
2.square
02.square
2.square.fill
02.square.fill
3.circle
03.circle
3.circle.fill
03.circle.fill
3.square
03.square
3.square.fill
03.square.fill
4.alt.circle
4.alt.circle.fill
4.alt.square
4.alt.square.fill
4.circle
04.circle
4.circle.fill
04.circle.fill
4.square
04.square
4.square.fill
04.square.fill
5.circle
05.circle
5.circle.fill
05.circle.fill
5.square
05.square
5.square.fill
05.square.fill
6.alt.circle
6.alt.circle.fill
6.alt.square
6.alt.square.fill
6.circle
06.circle
6.circle.fill
06.circle.fill
6.square
06.square
6.square.fill
06.square.fill
7.circle
07.circle
7.circle.fill
07.circle.fill
7.square
07.square
7.square.fill
07.square.fill
8.circle
08.circle
8.circle.fill
08.circle.fill
8.square
08.square
8.square.fill
08.square.fill
9.alt.circle
9.alt.circle.fill
9.alt.square
9.alt.square.fill
9.circle
09.circle
9.circle.fill
09.circle.fill
9.square
09.square
9.square.fill
09.square.fill
10.circle
10.circle.fill
10.square
10.square.fill
11.circle
11.circle.fill
11.square
11.square.fill
12.circle
12.circle.fill
12.square
12.square.fill
13.circle
13.circle.fill
13.square
13.square.fill
14.circle
14.circle.fill
14.square
14.square.fill
15.circle
15.circle.fill
15.square
15.square.fill
16.circle
16.circle.fill
16.square
16.square.fill
17.circle
17.circle.fill
17.square
17.square.fill
18.circle
18.circle.fill
18.square
18.square.fill
19.circle
19.circle.fill
19.square
19.square.fill
20.circle
20.circle.fill
20.square
20.square.fill
21.circle
21.circle.fill
21.square
21.square.fill
22.circle
22.circle.fill
22.square
22.square.fill
23.circle
23.circle.fill
23.square
23.square.fill
24.circle
24.circle.fill
24.square
24.square.fill
25.circle
25.circle.fill
25.square
25.square.fill
26.circle
26.circle.fill
26.square
26.square.fill
27.circle
27.circle.fill
27.square
27.square.fill
28.circle
28.circle.fill
28.square
28.square.fill
29.circle
29.circle.fill
29.square
29.square.fill
30.circle
30.circle.fill
30.square
30.square.fill
31.circle
31.circle.fill
31.square
31.square.fill
32.circle
32.circle.fill
32.square
32.square.fill
33.circle
33.circle.fill
33.square
33.square.fill
34.circle
34.circle.fill
34.square
34.square.fill
35.circle
35.circle.fill
35.square
35.square.fill
36.circle
36.circle.fill
36.square
36.square.fill
37.circle
37.circle.fill
37.square
37.square.fill
38.circle
38.circle.fill
38.square
38.square.fill
39.circle
39.circle.fill
39.square
39.square.fill
40.circle
40.circle.fill
40.square
40.square.fill
41.circle
41.circle.fill
41.square
41.square.fill
42.circle
42.circle.fill
42.square
42.square.fill
43.circle
43.circle.fill
43.square
43.square.fill
44.circle
44.circle.fill
44.square
44.square.fill
45.circle
45.circle.fill
45.square
45.square.fill
46.circle
46.circle.fill
46.square
46.square.fill
47.circle
47.circle.fill
47.square
47.square.fill
48.circle
48.circle.fill
48.square
48.square.fill
49.circle
49.circle.fill
49.square
49.square.fill
50.circle
50.circle.fill
50.square
50.square.fill
a
a.circle
a.circle.fill
a.square
a.square.fill
airplane
airplayaudio
Usage restricted to AirPlay
airplayvideo
Usage restricted to AirPlay
alarm
alarm.fill
alt
ant
ant.fill
antenna.radiowaves.left.and.right
app
app.badge
app.badge.fill
app.fill
app.gift
app.gift.fill
archivebox
archivebox.fill
arkit
Usage restricted to ARKit
arrow.2.circlepath
arrow.2.circlepath.circle
arrow.2.circlepath.circle.fill
arrow.2.squarepath
arrow.3.trianglepath
arrow.clockwise
arrow.clockwise.circle
arrow.clockwise.circle.fill
arrow.clockwise.icloud
Usage restricted to iCloud service
arrow.clockwise.icloud.fill
Usage restricted to iCloud service
arrow.counterclockwise
arrow.counterclockwise.circle
arrow.counterclockwise.circle.fill
arrow.counterclockwise.icloud
Usage restricted to iCloud service
arrow.counterclockwise.icloud.fill
Usage restricted to iCloud service
arrow.down
arrow.down.circle
arrow.down.circle.fill
arrow.down.doc
arrow.down.doc.fill
arrow.down.left
arrow.down.left.circle
arrow.down.left.circle.fill
arrow.down.left.square
arrow.down.left.square.fill
arrow.down.left.video
Usage restricted to FaceTime app
arrow.down.left.video.fill
Usage restricted to FaceTime app
arrow.down.right
arrow.down.right.and.arrow.up.left
arrow.down.right.circle
arrow.down.right.circle.fill
arrow.down.right.square
arrow.down.right.square.fill
arrow.down.square
arrow.down.square.fill
arrow.down.to.line
arrow.down.to.line.alt
arrow.left
arrow.left.and.right
arrow.left.and.right.circle
arrow.left.and.right.circle.fill
arrow.left.and.right.square
arrow.left.and.right.square.fill
arrow.left.circle
arrow.left.circle.fill
arrow.left.square
arrow.left.square.fill
arrow.left.to.line
arrow.left.to.line.alt
arrow.merge
arrow.right
arrow.right.arrow.left
arrow.right.arrow.left.circle
arrow.right.arrow.left.circle.fill
arrow.right.arrow.left.square
arrow.right.arrow.left.square.fill
arrow.right.circle
arrow.right.circle.fill
arrow.right.square
arrow.right.square.fill
arrow.right.to.line
arrow.right.to.line.alt
arrow.swap
arrow.turn.down.left
arrow.turn.down.right
arrow.turn.left.down
arrow.turn.left.up
arrow.turn.right.down
arrow.turn.right.up
arrow.turn.up.left
arrow.turn.up.right
arrow.up
arrow.up.and.down
arrow.up.and.down.circle
arrow.up.and.down.circle.fill
arrow.up.and.down.square
arrow.up.and.down.square.fill
arrow.up.arrow.down
arrow.up.arrow.down.circle
arrow.up.arrow.down.circle.fill
arrow.up.arrow.down.square
arrow.up.arrow.down.square.fill
arrow.up.bin
arrow.up.bin.fill
arrow.up.circle
arrow.up.circle.fill
arrow.up.doc
arrow.up.doc.fill
arrow.up.left
arrow.up.left.and.arrow.down.right
arrow.up.left.circle
arrow.up.left.circle.fill
arrow.up.left.square
arrow.up.left.square.fill
arrow.up.right
arrow.up.right.circle.fill
arrow.up.right.diamond
arrow.up.right.diamond.fill
arrow.up.right.square
arrow.up.right.square.fill
arrow.up.right.video
Usage restricted to FaceTime app
arrow.up.right.video.fill
Usage restricted to FaceTime app
arrow.up.square
arrow.up.square.fill
arrow.up.to.line
arrow.up.to.line.alt
arrow.upright.circle
arrow.uturn.down
arrow.uturn.down.circle
arrow.uturn.down.circle.fill
arrow.uturn.down.square
arrow.uturn.down.square.fill
arrow.uturn.left
arrow.uturn.left.circle
arrow.uturn.left.circle.fill
arrow.uturn.left.square
arrow.uturn.left.square.fill
arrow.uturn.right
arrow.uturn.right.circle
arrow.uturn.right.circle.fill
arrow.uturn.right.square
arrow.uturn.right.square.fill
arrow.uturn.up
arrow.uturn.up.circle
arrow.uturn.up.circle.fill
arrow.uturn.up.square
arrow.uturn.up.square.fill
arrowshape.turn.up.left
arrowshape.turn.up.left.2
arrowshape.turn.up.left.2.fill
arrowshape.turn.up.left.circle
arrowshape.turn.up.left.circle.fill
arrowshape.turn.up.left.fill
arrowshape.turn.up.right
arrowshape.turn.up.right.circle
arrowshape.turn.up.right.circle.fill
arrowshape.turn.up.right.fill
arrowtriangle.down
arrowtriangle.down.circle
arrowtriangle.down.circle.fill
arrowtriangle.down.fill
arrowtriangle.down.square
arrowtriangle.down.square.fill
arrowtriangle.left
arrowtriangle.left.circle
arrowtriangle.left.circle.fill
arrowtriangle.left.fill
arrowtriangle.left.square
arrowtriangle.left.square.fill
arrowtriangle.right
arrowtriangle.right.circle
arrowtriangle.right.circle.fill
arrowtriangle.right.fill
arrowtriangle.right.square
arrowtriangle.right.square.fill
arrowtriangle.up
arrowtriangle.up.circle
arrowtriangle.up.circle.fill
arrowtriangle.up.fill
arrowtriangle.up.square
arrowtriangle.up.square.fill
asterisk.circle
asterisk.circle.fill
at
at.badge.minus
at.badge.plus
australsign.circle
australsign.circle.fill
australsign.square
australsign.square.fill
b.circle
b.circle.fill
b.square
b.square.fill
backward
backward.end
backward.end.alt
backward.end.alt.fill
backward.end.fill
backward.fill
badge.plus.radiowaves.right
bag
bag.badge.minus
bag.badge.minus.fill
bag.badge.plus
bag.badge.plus.fill
bag.fill
bahtsign.circle
bahtsign.circle.fill
bahtsign.square
bahtsign.square.fill
bandage
bandage.fill
barcode
barcode.viewfinder
battery.0
battery.25
battery.100
bed.double
bed.double.fill
bell
bell.fill
bell.slash
bell.slash.fill
bin.xmark
bin.xmark.fill
bitcoinsign.circle
bitcoinsign.circle.fill
bitcoinsign.square
bitcoinsign.square.fill
bold
bold.italic.underline
bold.underline
bolt
bolt.fill
""".components(separatedBy: .whitespacesAndNewlines).shuffled().prefix(24).map(SymbolName.init)

let gridItems = Array(repeating: GridItem(.fixed(70), spacing: 45, alignment: .center), count: 6)
struct ContentView: View {
    var body: some View {
        ZStack {
            LazyHGrid(rows: gridItems, alignment: /*@START_MENU_TOKEN@*/.center/*@END_MENU_TOKEN@*/, spacing: 30.0, pinnedViews: /*@START_MENU_TOKEN@*/[]/*@END_MENU_TOKEN@*/, content: /*@START_MENU_TOKEN@*/{
                ForEach(symbols) {
                    Image(systemName: $0.name).resizable(capInsets: EdgeInsets(), resizingMode: .stretch)
                        .frame(width: 70, height: 70)
                        .scaledToFit()
                        
                        
                }
            })
            .padding(.bottom, 200.0)/*@END_MENU_TOKEN@*/
            .padding(.top, 85.0)
            Image(/*@START_MENU_TOKEN@*/"HomeScreen"/*@END_MENU_TOKEN@*/)
                .opacity(/*@START_MENU_TOKEN@*/0.1/*@END_MENU_TOKEN@*/)
        }
        
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
